= monorepo for cppfw libraries

Repositories of **cppfw** libraries are added as submodules under the `repos/` directory.

== Building with CMake

=== Prerequisites

- link:https://vcpkg.io[VCPKG] installed and `VCPKG_ROOT` environment variable set accordingly
- **Linux:** `pkg-config`, `zip`, `libgl1-mesa-dev`, `libgtk-3-dev` installed
+
```
sudo apt install pkg-config zip libgl1-mesa-dev libgtk-3-dev
```

=== Building

```
cd build/cmake
cmake . --preset rel
cmake --build --preset rel
```

Test applications binaries will be put to `out/rel/exe` directory.

Also `dbg` preset is available for debug builds. Replace `rel` with `dbg` in the above commands to build debug version.

=== Running apps

For example, if we want to run `ruis-app2` test application, we can do it like this:

```
cd build/cmake
cmake --build --preset rel --target run-ruis-app2-app-opengl
```

To list all cmake targets, one can use:
```
cmake --build --preset rel --target help
```

=== Building on Windows

Basically the same general steps are applicable for Windows.

To simplify the process, some command scripts are provided to automate the process of fetching submodules, installing vcpkg and generating Microsoft Visual Studio project.

**TODO: update these instructions, might be obsolete**

On Windows one can use the provided command scripts:

* `msvc2022_gen.cmd` - fetches submodules, installs vcpkg and generates Microsoft Visual Studio 2022 project
* `msvc2022_build.cmd` - generates Microsoft Visual Studio 2022 project and builds Release target
* `msvc2022_open.cmd` - generates Microsoft Visual Studio 2022 and opens it in the IDE

=== Adding your own projects

You can create your own applications inside `apps` subdirectory. Make sure to have your CMakeLists.txt inside
`apps/<your_app_name>/build/cmake` directory and build scripts will add it to the project automatically.
